language: python
sudo: false
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install .
script:
  - py.test
after_success:
  - pip install codeclimate-test-reporter
  - py.test --cov=tweetsave tests
  - CODECLIMATE_REPO_TOKEN="29bfabe1dcdaa62f0241face15255695ff00986b79c1c32f78bc9e276fe99da7" codeclimate-test-reporter
notifications:
  email: false
  slack:
    secure: nKvobT/phVDM8i/gBsutVecZrB7hSC5duc0j7KALMWEcjGCNlikDAE9O9FjMDmsDoEWr+0u51uIVa9kBJJ3Y1wbrfBNU+WpPlDkLuqUvFAuqIq+eXzVVEgAyH39JZgTs1h6eaLJHmpetHemazLWtbFBV+2/1HxEIsw+kN6kCCsafQn12ZaJouSmKptl27iwVlDiJE9u5xv2FZs80TUxUkf5nIgTKp0otfi1DCKN5mzOHtnFN/wOfqDFUBEsuQqBX6RIMAmFMGQejRP+Op9Op39Bd2Mg8vEPD0wpFqX3PZlqeUbd3MBGsuDs/a8KVXL+WrwXSXk4lPHqrQJhZ7o4xJ0EHkjKpPvvbFmPqceNpsvqofAU2fm1/6yqbmQfD2vxMS4iEFnJzAxFcnniEQLVK1azovLj5ovSxQeWQz80tKBTqVm4FwknBGdn4dkVqCeb5Ofi4+2P4xBSeAQiWFv/ypnT4pkfg26jq3RIyFvIUuIEjl6/57mld5WJKX8/3dxg6sHckNXKvZjgTbldT895k8o3xp62tu3Hnaim6eaMrA0IIgfkPSadBJY6xTs2XGIUJtRWGGWsEB9U0UGe1fWDQfS/OCdsu5UKtfndWgvaRhSEbxAyMsYyi8cCDzR0sgbUjIyCmPEAvoxnvlo3DpBmmqoSl+tWVNu5oB0sBGSIIPjc=
